name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'doc/*'
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: ['29.4']
        python-version: ['3.11']
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Build requirements
        run: 'pip install zensols.zotsite'

      - name: Setup Cask
        uses: conao3/setup-cask@master
        with:
          version: 'snapshot'

      - name: Run tests
        run: 'make test'
